import { FederativeUnitResponse } from './../../../../locality/federative-unit/integration/response/federative-unit.response';
import { NeighborhoodResponse } from './../../../../locality/neighborhood/integration/response/neighborhood.response';
import { CityResponse } from './../../../../locality/city/integration/response/city.response';
import { TransactionResponse } from './../../../transaction/integration/response/transaction.response';
import { FinalityResponse } from './../../../finality/integration/response/finality.response';
import { SituationResponse } from './../../../../user/integration/response/situation.response';
import { AgentResponse } from './../../../../agent/integration/response/agent.response';
import { ZoneResponse } from './../../../zone/integration/response/zone.response';
import { ProfileResponse } from './../../../profile/integration/response/profile.response';
import { ConservationStateResponse } from './../../../conservation-state/integration/response/conservation-state.response';
import { TypeResponse } from './../../../type/integration/response/type.response';
import { CategoryResponse } from './../../../category/integration/response/category.response';

export class PropertyDetailResponse {
    public code?: number;
    public internalCode?: number;
    public title?: string;
    public price?: string;
    public dormitory?: number;
    public unitAvailable?: number;
    public bathroom?: number;
    public parkingVacancy?: number;
    public privativeArea?: string;
    public totalArea?: string;
    public pavement?: number;
    public financeable?: boolean;
    public description?: string;
    public privateInfo?: string;
    public show?: boolean;
    public reserved?: boolean;
    public reserveDate?: string;
    public hectare?: number;
    public constuctionYear?: number;
    public featured?: boolean;
    public superFeatured?: boolean;
    public suite?: number;
    public rented?: boolean;
    public condominiumPrice?: string;
    public showValue?: boolean;
    public city?: CityResponse;
    public neighborhood?: NeighborhoodResponse;
    public zipCode?: string;
    public street?: string;
    public number?: string;
    public complement?: string;
    public latitude?: string;
    public longitude?: string;
    public mainPhoto: string;
    public category?: CategoryResponse;
    public type?: TypeResponse;
    public conservationState?: ConservationStateResponse;
    public profile?: ProfileResponse;
    public zone?: ZoneResponse;
    public agent?: AgentResponse;
    public situation?: SituationResponse;
    public finality?: FinalityResponse;
    public transaction?: TransactionResponse;
    public federativeUnit?: FederativeUnitResponse;
}
