version: '3'

name: integrador

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4200:4200"
      - "49153:49153"
    volumes:
      - ./:/home/app
      - ./command.sh:/home/utils/command.sh
