version: '3'
 
services:
  imob7-db:
    build: ./database/
    container_name: imob7-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - imob7-dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - imob7-db
    environment:
      PMA_HOST: imob7-db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 3307:80
volumes:
  imob7-dbdata: