version: "3.6"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: imob7
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - .:/home/app
      - ./command.sh:/home/utils/command.sh
