export const environment = {
  production: true,
  endpoint: {
    viaCep: "https://viacep.com.br",
    user: "http://api.imobiliaria7setembro.com.br/user",
    neighborhood: "http://api.imobiliaria7setembro.com.br/neighborhood",
    city: "http://api.imobiliaria7setembro.com.br/locality/city",
    uf: "http://api.imobiliaria7setembro.com.br/locality/uf",
    agent: "http://api.imobiliaria7setembro.com.br/agent",
    auth: "http://api.imobiliaria7setembro.com.br/auth",
    blog: "http://api.imobiliaria7setembro.com.br/blog",
    configuration: "http://api.imobiliaria7setembro.com.br/configuration",
    banner: "http://api.imobiliaria7setembro.com.br/banner",
    locality: "http://api.imobiliaria7setembro.com.br/locality",
    property: "http://api.imobiliaria7setembro.com.br/property",
    contact: "http://api.imobiliaria7setembro.com.br/contact",
    cdn: "http://cdn.imobiliaria7setembro.com.br/",
    partner: "http://api.imobiliaria7setembro.com.br/partner",
  },
  cdn: "http://cdn.imobiliaria7setembro.com.br",
};
